import "dotenv/config";
import { PrismaClient } from "../app/generated/prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) throw new Error("DATABASE_URL is not defined");

const adapter = new PrismaNeon({ connectionString });
const prisma = new PrismaClient({ adapter });

interface ActivityData {
  code: string;
  projetCode: string;
  titre: string;
  nature: string | null;
  lieu: string | null;
  budget: number;
  isParent: boolean;
}

const ACTIVITES: ActivityData[] = [
  { code: "P1.PNR1.1-A.1", projetCode: "P1.PNR1.1", titre: "Offrir les services SSR dans les centres de l'AIBEF", nature: null, lieu: null, budget: 231518660, isParent: true },
  { code: "P1.PNR1.1-A.1.1", projetCode: "P1.PNR1.1", titre: "Offrir les services SSR dans le centre de Treichville", nature: "Consultation Clinique", lieu: "Treichville", budget: 47660000, isParent: false },
  { code: "P1.PNR1.1-A.1.2", projetCode: "P1.PNR1.1", titre: "Offrir les services SSR dans le centre du CASEJ", nature: "Consultation Clinique", lieu: "Yopougon", budget: 17411000, isParent: false },
  { code: "P1.PNR1.1-A.1.3", projetCode: "P1.PNR1.1", titre: "Offrir les services SSR dans le centre de Bouaké", nature: "Consultation Clinique", lieu: "Bouaké", budget: 21545250, isParent: false },
  { code: "P1.PNR1.1-A.1.4", projetCode: "P1.PNR1.1", titre: "Offrir les services SSR dans le centre de Daloa", nature: "Consultation Clinique", lieu: "Daloa", budget: 24037930, isParent: false },
  { code: "P1.PNR1.1-A.1.5", projetCode: "P1.PNR1.1", titre: "Offrir les services SSR dans le centre de Korhogo", nature: "Consultation Clinique", lieu: "Korhogo", budget: 62605730, isParent: false },
  { code: "P1.PNR1.1-A.1.6", projetCode: "P1.PNR1.1", titre: "Offrir les services SSR dans le centre de Man", nature: "Consultation Clinique", lieu: "Man", budget: 12461250, isParent: false },
  { code: "P1.PNR1.1-A.1.7", projetCode: "P1.PNR1.1", titre: "Offrir les services SSR dans le centre de San Pedro", nature: "Consultation Clinique", lieu: "San Pedro", budget: 23390650, isParent: false },
  { code: "P1.PNR1.1-A.1.8", projetCode: "P1.PNR1.1", titre: "Offrir les services SSR dans le centre de Yamoussoukro", nature: "Consultation Clinique", lieu: "Yamoussoukro", budget: 22406850, isParent: false },
  { code: "P1.PR1.1-A.2", projetCode: "P1.PR1.1", titre: "Organiser les missions d’approvisionnement des centres de l’AIBEF", nature: null, lieu: null, budget: 605425, isParent: true },
  { code: "P1.PNR1.1-A.2.1", projetCode: "P1.PNR1.1", titre: "Organiser la 1er  mission d’approvisionnement des centres de l’AIBEF", nature: "Livraison", lieu: "Siège", budget: 605425, isParent: false },
  { code: "P1.PNR1.1-A.2.2", projetCode: "P1.PNR1.1", titre: "Organiser la 2ième  mission d’approvisionnement des centres de l’AIBEF", nature: "Livraison", lieu: "Siège", budget: 0, isParent: false },
  { code: "P1.PNR1.1-A.3", projetCode: "P1.PNR1.1", titre: "Organiser les inventaires des produits PPS de l’AIBEF", nature: null, lieu: null, budget: 5432000, isParent: true },
  { code: "P1.PNR1.1-A.3.1", projetCode: "P1.PNR1.1", titre: "Organiser l'inventaire des produits des cliniques d'Abidjan", nature: "Inventaire", lieu: "Siège", budget: 2097000, isParent: false },
  { code: "P1.PNR1.1-A.3.2", projetCode: "P1.PNR1.1", titre: "Organiser l'inventaire des produits de la clinique de Bouaké", nature: "Inventaire", lieu: "Bouaké", budget: 320000, isParent: false },
  { code: "P1.PNR1.1-A.3.3", projetCode: "P1.PNR1.1", titre: "Organiser l'inventaire des produits de la clinique de Daloa", nature: "Inventaire", lieu: "Daloa", budget: 640000, isParent: false },
  { code: "P1.PNR1.1-A.3.4", projetCode: "P1.PNR1.1", titre: "Organiser l'inventaire des produits de la clinique de Korhogo", nature: "Inventaire", lieu: "Korhogo", budget: 720000, isParent: false },
  { code: "P1.PNR1.1-A.3.5", projetCode: "P1.PNR1.1", titre: "Organiser l'inventaire des produits de la clinique de Man", nature: "Inventaire", lieu: "Man", budget: 360000, isParent: false },
  { code: "P1.PNR1.1-A.3.6", projetCode: "P1.PNR1.1", titre: "Organiser l'inventaire des produits de la clinique de San Pedro", nature: "Inventaire", lieu: "San Pedro", budget: 875000, isParent: false },
  { code: "P1.PNR1.1-A.3.7", projetCode: "P1.PNR1.1", titre: "Organiser l'inventaire des produits de la clinique de  Yamoussoukro", nature: "Inventaire", lieu: "Yamoussoukro", budget: 420000, isParent: false },
  { code: "P1.PNR1.1-A.4", projetCode: "P1.PNR1.1", titre: "Acquérir les produits et équipements", nature: null, lieu: null, budget: 0, isParent: true },
  { code: "P1.PNR1.1-A.4.1", projetCode: "P1.PNR1.1", titre: "Acquérir du matériel (mobiliers de bureau et équipements)  et autres fournitures", nature: "Achat", lieu: "Siège", budget: 0, isParent: false },
  { code: "P1.PNR1.1-A.4.2", projetCode: "P1.PNR1.1", titre: "Acquérir  des produits de santé et autres produits", nature: "Achat", lieu: "Siège", budget: 0, isParent: false },
  { code: "P1.PR1.1-A.1", projetCode: "P1.PR1.1", titre: "Organiser une campagne digitale pour la promotion des services offerts", nature: null, lieu: null, budget: 450000, isParent: true },
  { code: "P1.PR1.1-A.1.1", projetCode: "P1.PR1.1", titre: "Organiser la 1ère campagne digitale pour la promotion des services d", nature: "Sensibilisation", lieu: "Siège", budget: 450000, isParent: false },
  { code: "P1.PR1.1-A.2", projetCode: "P1.PR1.1", titre: "Organiser des journées portes ouvertes dans les cliniques de l’AIBEF", nature: null, lieu: null, budget: 4120000, isParent: true },
  { code: "P1.PR1.1-A.2.1", projetCode: "P1.PR1.1", titre: "Organiser la journée porte ouverte dans la clinique de Treichville", nature: "Sensibilisation", lieu: "Treichville", budget: 483750, isParent: false },
  { code: "P1.PR1.1-A.2.2", projetCode: "P1.PR1.1", titre: "Organiser la journée porte ouverte dans la clinique du CASEJ", nature: "Sensibilisation", lieu: "Yopougon", budget: 483750, isParent: false },
  { code: "P1.PR1.1-A.2.3", projetCode: "P1.PR1.1", titre: "Organiser la journée porte ouverte dans la clinique de Bouaké", nature: "Sensibilisation", lieu: "Bouaké", budget: 502500, isParent: false },
  { code: "P1.PR1.1-A.2.4", projetCode: "P1.PR1.1", titre: "Organiser la journée porte ouverte dans la clinique de Daloa", nature: "Sensibilisation", lieu: "Daloa", budget: 500000, isParent: false },
  { code: "P1.PR1.1-A.2.5", projetCode: "P1.PR1.1", titre: "Organiser la journée porte ouverte dans la clinique de Korhogo", nature: "Sensibilisation", lieu: "Korhogo", budget: 525000, isParent: false },
  { code: "P1.PR1.1-A.2.6", projetCode: "P1.PR1.1", titre: "Organiser la journée porte ouverte dans la clinique de Man", nature: "Sensibilisation", lieu: "Man", budget: 562500, isParent: false },
  { code: "P1.PR1.1-A.2.7", projetCode: "P1.PR1.1", titre: "Organiser la journée porte ouverte dans la clinique de San Pedro", nature: "Sensibilisation", lieu: "San Pedro", budget: 537500, isParent: false },
  { code: "P1.PR1.1-A.2.8", projetCode: "P1.PR1.1", titre: "Organiser la journée porte ouverte dans la clinique de Yamoussoukro", nature: "Sensibilisation", lieu: "Yamoussoukro", budget: 525000, isParent: false },
  { code: "P1.PR1.1-A.3", projetCode: "P1.PR1.1", titre: "Offrir les services de SR/PF en stratégie avancée", nature: null, lieu: null, budget: 7860500, isParent: true },
  { code: "P1.PR1.1-A.3.1", projetCode: "P1.PR1.1", titre: "Organiser des consultations foraines à Abidjan", nature: "Consultation Foraine", lieu: "Siège", budget: 1851500, isParent: false },
  { code: "P1.PR1.1-A.3.2", projetCode: "P1.PR1.1", titre: "Organiser des consultations foraines à Bouaké", nature: "Consultation Foraine", lieu: "Bouaké", budget: 1001500, isParent: false },
  { code: "P1.PR1.1-A.3.3", projetCode: "P1.PR1.1", titre: "Organiser des consultations foraines à Daloa", nature: "Consultation Foraine", lieu: "Daloa", budget: 1001500, isParent: false },
  { code: "P1.PR1.1-A.3.4", projetCode: "P1.PR1.1", titre: "Organiser des consultations foraines à Korhogo", nature: "Consultation Foraine", lieu: "Korhogo", budget: 1001500, isParent: false },
  { code: "P1.PR1.1-A.3.5", projetCode: "P1.PR1.1", titre: "Organiser des consultations foraines à Man", nature: "Consultation Foraine", lieu: "Man", budget: 1001500, isParent: false },
  { code: "P1.PR1.1-A.3.6", projetCode: "P1.PR1.1", titre: "Organiser des consultations foraines à San Pedro", nature: "Consultation Foraine", lieu: "San Pedro", budget: 1001500, isParent: false },
  { code: "P1.PR1.1-A.3.7", projetCode: "P1.PR1.1", titre: "Organiser des consultations foraines à Yamoussoukro", nature: "Consultation Foraine", lieu: "Yamoussoukro", budget: 1001500, isParent: false },
  { code: "P1.PR1.1-A.4", projetCode: "P1.PR1.1", titre: "Elargir la gamme de services dans les cliniques AIBEF", nature: null, lieu: null, budget: 8510000, isParent: true },
  { code: "P1.PR1.1-A.4.1", projetCode: "P1.PR1.1", titre: "Frais de fonctionnement de la clinique de Treichville", nature: "Fonctionnement", lieu: "Siège", budget: 2485000, isParent: false },
  { code: "P1.PR1.1-A.4.2", projetCode: "P1.PR1.1", titre: "Frais de fonctionnement de la clinique de Bouaké", nature: "Fonctionnement", lieu: "Bouaké", budget: 1175000, isParent: false },
  { code: "P1.PR1.1-A.4.3", projetCode: "P1.PR1.1", titre: "Frais de fonctionnement de la clinique de Daloa", nature: "Fonctionnement", lieu: "Daloa", budget: 1225000, isParent: false },
  { code: "P1.PR1.1-A.4.4", projetCode: "P1.PR1.1", titre: "Frais de fonctionnement de la clinique de Korhogo", nature: "Fonctionnement", lieu: "Korhogo", budget: 1165000, isParent: false },
  { code: "P1.PR1.1-A.4.5", projetCode: "P1.PR1.1", titre: "Frais de fonctionnement de la clinique de Man", nature: "Fonctionnement", lieu: "Man", budget: 620000, isParent: false },
  { code: "P1.PR1.1-A.4.6", projetCode: "P1.PR1.1", titre: "Frais de fonctionnement de la clinique de San Pedro", nature: "Fonctionnement", lieu: "San Pedro", budget: 920000, isParent: false },
  { code: "P1.PR1.1-A.4.7", projetCode: "P1.PR1.1", titre: "Frais de fonctionnement de la clinique de Yamoussoukro", nature: "Fonctionnement", lieu: "Yamoussoukro", budget: 920000, isParent: false },
  { code: "P1.PR1.1-A.5", projetCode: "P1.PR1.1", titre: "Organiser des réunions de coordination", nature: null, lieu: null, budget: 792000, isParent: true },
  { code: "P1.PR1.1-A.5.1", projetCode: "P1.PR1.1", titre: "Organiser la 1ère réunion de coordination", nature: "Réunion", lieu: "Siège", budget: 792000, isParent: false },
  { code: "P1.PR1.2-A.1", projetCode: "P1.PR1.2", titre: "Organiser des campagnes de communication de masse (radios locales) dans les  zones ciblées", nature: null, lieu: null, budget: 11163630, isParent: true },
  { code: "P1.PR1.2-A.1.1", projetCode: "P1.PR1.2", titre: "Participer à un atelier de conception et de validation des contenus des messages audio/écrits et des supports de communication", nature: "Atelier", lieu: "Siège", budget: 975000, isParent: false },
  { code: "P1.PR1.2-A.1.2", projetCode: "P1.PR1.2", titre: "Participer à un atelier de formation des acteurs de radios locales", nature: "Atelier", lieu: "Siège", budget: 975000, isParent: false },
  { code: "P1.PR1.2-A.1.3", projetCode: "P1.PR1.2", titre: "Produire les supports de communication", nature: "Production", lieu: "Siège", budget: 7935000, isParent: false },
  { code: "P1.PR1.2-A.1.4", projetCode: "P1.PR1.2", titre: "Organiser une mission de livraison du matériel et supports de communication du niveau central vers les antennes de Man, Korhogo, Daloa, San Pedro et Soubré", nature: "Livraison", lieu: "Siège", budget: 923405, isParent: false },
  { code: "P1.PR1.2-A.1.5", projetCode: "P1.PR1.2", titre: "Organiser des missions de livraison du matériel et supports de communication a partir des antennes vers  les centres franchisés privés du projet", nature: "Livraison", lieu: "Siège", budget: 355225, isParent: false },
  { code: "P1.PR1.2-A.2", projetCode: "P1.PR1.2", titre: "Organiser des campagnes de Communication interpersonnelle dans les zones ciblées", nature: null, lieu: null, budget: 42697910, isParent: true },
  { code: "P1.PR1.2-A.2.1", projetCode: "P1.PR1.2", titre: "Organiser en collaboration avec les  autres PE une mission de présentation du projet dans les zones de mise en œuvre", nature: "Supervision", lieu: "Siège", budget: 8662910, isParent: false },
  { code: "P1.PR1.2-A.2.2", projetCode: "P1.PR1.2", titre: "Organiser des  séances de CCC dans les  IFEF, les  Centres d'Ecoute et de Conseil dans les zones du projet", nature: "Sensibilisation", lieu: "Siège", budget: 20700000, isParent: false },
  { code: "P1.PR1.2-A.2.3", projetCode: "P1.PR1.2", titre: "Doter les ASCs en équipements de sensibilisation, de communication", nature: "Achat", lieu: "Siège", budget: 1185000, isParent: false },
  { code: "P1.PR1.2-A.2.4", projetCode: "P1.PR1.2", titre: "Organiser les  séances de causeries de groupes et visites à domicile par les ASCs", nature: "Sensibilisation", lieu: "Siège", budget: 12150000, isParent: false },
  { code: "P1.PR1.2-A.3", projetCode: "P1.PR1.2", titre: "Faire un appui aux structures privées afin de fournir des services de qualité de PF par le biais de la Franchise Sociale", nature: null, lieu: null, budget: 26780000, isParent: true },
  { code: "P1.PR1.2-A.3.1", projetCode: "P1.PR1.2", titre: "Organiser un atelier de révision du protocole de franchise sociale y compris la stratégie d’autonomisation", nature: "Atelier", lieu: "Siège", budget: 330000, isParent: false },
  { code: "P1.PR1.2-A.3.2", projetCode: "P1.PR1.2", titre: "Organiser un atelier de formation des prestataires des structures sélectionnées en technologie contraceptive", nature: "Atelier", lieu: "Siège", budget: 10949000, isParent: false },
  { code: "P1.PR1.2-A.3.3", projetCode: "P1.PR1.2", titre: "Doter les  15 centres franchisés en matériels et consommables médicaux", nature: "Achat", lieu: "Siège", budget: 15501000, isParent: false },
  { code: "P1.PR1.2-A.4", projetCode: "P1.PR1.2", titre: "Organiser  les  consultations foraines dans les zones de mise en œuvre du projet", nature: null, lieu: null, budget: 8081780, isParent: true },
  { code: "P1.PR1.2-A.4.1", projetCode: "P1.PR1.2", titre: "Organiser  la 1ière  consultation foraine dans les zones de mise en œuvre du projet", nature: "Consultation Foraine", lieu: "Siège", budget: 4040890, isParent: false },
  { code: "P1.PR1.2-A.4.2", projetCode: "P1.PR1.2", titre: "Organiser  la 2ième  consultation foraine dans les zones de mise en œuvre du projet", nature: "Consultation Foraine", lieu: "Siège", budget: 4040890, isParent: false },
  { code: "P1.PR1.2-A.5", projetCode: "P1.PR1.2", titre: "Renforcer les capacités des ASCs pour l’offre de méthodes : préservatifs, pilules et Sayana Press dans les zones ciblées", nature: null, lieu: null, budget: 14524648, isParent: true },
  { code: "P1.PR1.2-A.5.1", projetCode: "P1.PR1.2", titre: "Organiser une session d’orientation des ASCs sur CCSC/SBC en SR/PF et  sur la gestion des outils de collectes", nature: "Atelier", lieu: "Siège", budget: 8011000, isParent: false },
  { code: "P1.PR1.2-A.5.2", projetCode: "P1.PR1.2", titre: "Produire les outils de collecte de données PF pour les ASCs", nature: "Production", lieu: "Siège", budget: 6513648, isParent: false },
  { code: "P1.PR1.2-A.6", projetCode: "P1.PR1.2", titre: "Organiser les visites de suivi et de collecte des données", nature: null, lieu: null, budget: 6831920, isParent: true },
  { code: "P1.PR1.2-A.6.1", projetCode: "P1.PR1.2", titre: "Organiser la 1ière visite de suivi des activités des ASCs par les districts sanitaires", nature: "Suivi", lieu: "Siège", budget: 637500, isParent: false },
  { code: "P1.PR1.2-A.6.2", projetCode: "P1.PR1.2", titre: "Organiser la 2ième visite de suivi des activités des ASCs par les districts sanitaires", nature: "Suivi", lieu: "Siège", budget: 637500, isParent: false },
  { code: "P1.PR1.2-A.6.3", projetCode: "P1.PR1.2", titre: "Organiser la 1ière visite de collecte des données dans les centres franchisés", nature: "Suivi", lieu: "Siège", budget: 1389230, isParent: false },
  { code: "P1.PR1.2-A.6.4", projetCode: "P1.PR1.2", titre: "Organiser la 2ième visite de collecte des données dans les centres franchisés", nature: "Suivi", lieu: "Siège", budget: 1389230, isParent: false },
  { code: "P1.PR1.2-A.6.5", projetCode: "P1.PR1.2", titre: "Organiser la 1ière visite de supervision dans les zones d'intervention du projet", nature: "Supervision", lieu: "Siège", budget: 1389230, isParent: false },
  { code: "P1.PR1.2-A.6.6", projetCode: "P1.PR1.2", titre: "Organiser la 2ième visite de supervision dans les zones d'intervention du projet", nature: "Supervision", lieu: "Siège", budget: 1389230, isParent: false },
  { code: "P1.PR1.2-A.7", projetCode: "P1.PR1.2", titre: "Organiser des ateliers", nature: null, lieu: null, budget: 6770000, isParent: true },
  { code: "P1.PR1.2-A.7.1", projetCode: "P1.PR1.2", titre: "Organiser un atelier de co – création du Plan de suivi/évaluation du projet avec les Partenaires d’Exécution", nature: "Atelier", lieu: "Siège", budget: 4510000, isParent: false },
  { code: "P1.PR1.2-A.7.2", projetCode: "P1.PR1.2", titre: "Participer à la réunion bilan annuel et de partage des résultats du projet", nature: "Atelier", lieu: "Siège", budget: 2260000, isParent: false },
  { code: "P1.PR1.2-A.8", projetCode: "P1.PR1.2", titre: "Organisation des missions de supervision dans les zones d'intervention", nature: null, lieu: null, budget: 11500190, isParent: true },
  { code: "P1.PR1.2-A.8.1", projetCode: "P1.PR1.2", titre: "Organiser la 1ière mission conjointe de supervision semestrielle du niveau central de l’équipe Programme, Suivi-Evaluation et Finance", nature: "Supervision", lieu: "Siège", budget: 3962910, isParent: false },
  { code: "P1.PR1.2-A.8.2", projetCode: "P1.PR1.2", titre: "Organiser la 2ième mission conjointe de supervision semestrielle du niveau central de l’équipe Programme, Suivi-Evaluation et Finance", nature: "Supervision", lieu: "Siège", budget: 3962910, isParent: false },
  { code: "P1.PR1.2-A.8.3", projetCode: "P1.PR1.2", titre: "Organiser la 1ière mission de supervision cliniques semestrielle du niveau central et local", nature: "Supervision", lieu: "Siège", budget: 1787185, isParent: false },
  { code: "P1.PR1.2-A.8.4", projetCode: "P1.PR1.2", titre: "Organiser la 2ième mission de supervision cliniques semestrielle du niveau central et local", nature: "Supervision", lieu: "Siège", budget: 1787185, isParent: false },
  { code: "P1.PR1.2-A.9", projetCode: "P1.PR1.2", titre: "Participer aux réunion de coordination et de suivi du projet", nature: null, lieu: null, budget: 400000, isParent: true },
  { code: "P1.PR1.2-A.9.1", projetCode: "P1.PR1.2", titre: "Participer à la 1ière réunion de coordinations et de suivi des activités organisées par le PNSME", nature: "Réunion", lieu: "Siège", budget: 64000, isParent: false },
  { code: "P1.PR1.2-A.9.2", projetCode: "P1.PR1.2", titre: "Participer à la 2ième réunion de coordinations et de suivi des activités organisées par le PNSME", nature: "Réunion", lieu: "Siège", budget: 64000, isParent: false },
  { code: "P1.PR1.2-A.9.3", projetCode: "P1.PR1.2", titre: "Participer à la 3ième réunion de coordinations et de suivi des activités organisées par le PNSME", nature: "Réunion", lieu: "Siège", budget: 64000, isParent: false },
  { code: "P1.PR1.2-A.9.4", projetCode: "P1.PR1.2", titre: "Participer à la 4ième réunion de coordinations et de suivi des activités organisées par le PNSME", nature: "Réunion", lieu: "Siège", budget: 64000, isParent: false },
  { code: "P1.PR1.2-A.9.5", projetCode: "P1.PR1.2", titre: "Participer à la 1ière réunion de suivi des activités entre PE", nature: "Réunion", lieu: "Siège", budget: 48000, isParent: false },
  { code: "P1.PR1.2-A.9.6", projetCode: "P1.PR1.2", titre: "Participer à la 2ième réunion de suivi des activités entre PE", nature: "Réunion", lieu: "Siège", budget: 48000, isParent: false },
  { code: "P1.PR1.2-A.9.7", projetCode: "P1.PR1.2", titre: "Participer à la 3ième réunion de suivi des activités entre PE", nature: "Réunion", lieu: "Siège", budget: 48000, isParent: false },
  { code: "P1.PNR3.1 -A.1", projetCode: "P1.PNR3.1", titre: "Offrir des services de téléconseils", nature: null, lieu: null, budget: 1348000, isParent: true },
  { code: "P1.PNR3.1 -A.1.1", projetCode: "P1.PNR3.1", titre: "Organiser des activités d'information sur l’existence du service de téléconseils", nature: null, lieu: "Siège", budget: 740000, isParent: false },
  { code: "P1.PNR3.1 -A.1.2", projetCode: "P1.PNR3.1", titre: "Prime des MAJ pour animation de la plateforme", nature: null, lieu: "Siège", budget: 96000, isParent: false },
  { code: "P1.PNR3.1 -A.1.3", projetCode: "P1.PNR3.1", titre: "Orienter  les animateurs sur l'algorithme", nature: null, lieu: "Siège", budget: 512000, isParent: false },
  { code: "P2.PNR3.4-A.1", projetCode: "P2.PNR3.4", titre: "Organiser les activités en direction des ado/jeunes", nature: null, lieu: null, budget: 35702000, isParent: true },
  { code: "P2.PNR3.4-A.1.1", projetCode: "P2.PNR3.4", titre: "Organiser des sessions de formation en ligne à l'endroit des MAJ pour renforcer leurs compétences", nature: null, lieu: "Siège", budget: 2605000, isParent: false },
  { code: "P2.PNR3.4-A.1.2", projetCode: "P2.PNR3.4", titre: "Organiser des journées thématiques des MAJ dans les antennes", nature: null, lieu: "Yopougon", budget: 6150000, isParent: false },
  { code: "P2.PNR3.4-A.1.3", projetCode: "P2.PNR3.4", titre: "Offrir des services multimédia dans le CASEJ", nature: null, lieu: "Yopougon", budget: 26095000, isParent: false },
  { code: "P2.PNR3.4-A.1.4", projetCode: "P2.PNR3.4", titre: "Participer aux journées Commémoratifs (JIJ, JMC, JMLS, JEA, etc,)", nature: null, lieu: "Siège", budget: 852000, isParent: false },
  { code: "P2.PR2.1-A.1.1", projetCode: "P2.PR2.1", titre: "Mener des activités de recherche active/sensibilisation pour l'identification de 100  survivantes de FO", nature: "Sensibilisation", lieu: "Siège", budget: 1180000, isParent: false },
  { code: "P2.PR2.1-A.1.2", projetCode: "P2.PR2.1", titre: "Assurer le paiement des frais de transport et de nutrition des survivantes de FO lors des missions opératoires", nature: "Fonctionnement", lieu: "Siège", budget: 8300000, isParent: false },
  { code: "P2.PR3.2-A.1", projetCode: "P2.PR3.2", titre: "Organiser des activités de sensibilisation de masse", nature: null, lieu: null, budget: 1080000, isParent: true },
  { code: "P2.PR3.2-A.1.1", projetCode: "P2.PR3.2", titre: "Organiser la 1ière activité de sensibilisation de masse", nature: "Sensibilisation", lieu: "Daloa", budget: 540000, isParent: false },
  { code: "P2.PR3.2-A.1.2", projetCode: "P2.PR3.2", titre: "Organiser la 2ième activité de sensibilisation de masse", nature: "Sensibilisation", lieu: "Daloa", budget: 540000, isParent: false },
  { code: "P2.PR3.2-A.1", projetCode: "P2.PR3.2", titre: "Organiser des ateliers d’ESC", nature: null, lieu: null, budget: 720000, isParent: true },
  { code: "P2.PR3.2-A.1.1", projetCode: "P2.PR3.2", titre: "Organiser le 1er atelier d’ESC", nature: "Atelier", lieu: "Daloa", budget: 180000, isParent: false },
  { code: "P2.PR3.2-A.1.2", projetCode: "P2.PR3.2", titre: "Organiser le 2ième atelier d’ESC", nature: "Atelier", lieu: "Daloa", budget: 180000, isParent: false },
  { code: "P2.PR3.2-A.1.3", projetCode: "P2.PR3.2", titre: "Organiser le 3ième atelier d’ESC", nature: "Atelier", lieu: "Daloa", budget: 180000, isParent: false },
  { code: "P2.PR3.2-A.1.4", projetCode: "P2.PR3.2", titre: "Organiser le 4ième atelier d’ESC", nature: "Atelier", lieu: "Daloa", budget: 180000, isParent: false },
  { code: "P2.PR3.2-A.2", projetCode: "P2.PR3.2", titre: "Organiser des rencontres de renforcement de capacités des acteurs communautaires", nature: null, lieu: null, budget: 1036000, isParent: true },
  { code: "P2.PR3.2-A.2.1", projetCode: "P2.PR3.2", titre: "Organiser une session de renforcement de capacités des acteurs communautaires", nature: "Atelier", lieu: "Daloa", budget: 1036000, isParent: false },
  { code: "P2.PR3.2-A.3", projetCode: "P2.PR3.2", titre: "Mettre en place les écoles des maris et écoles des futures", nature: null, lieu: null, budget: 14100000, isParent: true },
  { code: "P2.PR3.2-A.3.1", projetCode: "P2.PR3.2", titre: "Mettre en place les écoles des maris", nature: "Atelier", lieu: "Daloa", budget: 7050000, isParent: false },
  { code: "P2.PR3.2-A.3.2", projetCode: "P2.PR3.2", titre: "Mettre en place les écoles des futurs maris", nature: "Atelier", lieu: "Daloa", budget: 7050000, isParent: false },
  { code: "P3.PNR3.1-A.1", projetCode: "P3.PNR1.1", titre: "Organiser des ateliers", nature: null, lieu: null, budget: 7140000, isParent: true },
  { code: "P3.PNR3.1-A.1.1", projetCode: "P3.PNR1.1", titre: "Organiser un atelier d'élaboration des activités du BP 2027  - 2029", nature: "Atelier", lieu: "Siège", budget: 3060000, isParent: false },
  { code: "P3.PNR3.1-A.1.2", projetCode: "P3.PNR1.1", titre: "Organiser un atelier d'orientation des prestataires sur les nouveaux indicateurs de l'IPPF", nature: "Atelier", lieu: "Siège", budget: 4080000, isParent: false },
  { code: "P3.PNR1.1-A.2", projetCode: "P3.PNR1.1", titre: "Organiser des réunions de coordination et de suivi", nature: null, lieu: null, budget: 255000, isParent: true },
  { code: "P3.PNR1.1-A.2.1", projetCode: "P3.PNR1.1", titre: "Organiser la 1ière réunion de coordination en ligne des activités du BP", nature: "Réunion", lieu: "Siège", budget: 127500, isParent: false },
  { code: "P3.PNR1.1-A.2.2", projetCode: "P3.PNR1.1", titre: "Organiser la 2ième réunion de coordination en ligne des activités du BP", nature: "Réunion", lieu: "Siège", budget: 127500, isParent: false },
  { code: "P3.PNR1.1-A.3", projetCode: "P3.PNR1.1", titre: "Organiser des visites de collecte des données et de coaching des prestataires dans les centres franchisés", nature: null, lieu: null, budget: 1890000, isParent: true },
  { code: "P3.PNR1.1-A.3.1", projetCode: "P3.PNR1.1", titre: "Organiser la 1ière visite de collecte des données et de coaching des prestataires dans les centres franchisés à Abidjan", nature: "Suivi", lieu: "Siège", budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.2", projetCode: "P3.PNR1.1", titre: "Organiser la 2ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Abidjan", nature: "Suivi", lieu: "Siège", budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.3", projetCode: "P3.PNR1.1", titre: "Organiser la 3ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Abidjan", nature: "Suivi", lieu: "Siège", budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.4", projetCode: "P3.PNR1.1", titre: "Organiser la 4ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Abidjan", nature: "Suivi", lieu: "Siège", budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.5", projetCode: "P3.PNR1.1", titre: "Organiser la 1ière visite de collecte des données et de coaching des prestataires dans les centres franchisés à Bouaké", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.6", projetCode: "P3.PNR1.1", titre: "Organiser la 2ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Bouaké", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.7", projetCode: "P3.PNR1.1", titre: "Organiser la 3ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Bouaké", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.8", projetCode: "P3.PNR1.1", titre: "Organiser la 4ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Bouaké", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.9", projetCode: "P3.PNR1.1", titre: "Organiser la 1ière visite de collecte des données et de coaching des prestataires dans les centres franchisés à Daloa", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.10", projetCode: "P3.PNR1.1", titre: "Organiser la 2ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Daloa", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.11", projetCode: "P3.PNR1.1", titre: "Organiser la 3ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Daloa", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.12", projetCode: "P3.PNR1.1", titre: "Organiser la 4ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Daloa", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.13", projetCode: "P3.PNR1.1", titre: "Organiser la 1ière visite de collecte des données et de coaching des prestataires dans les centres franchisés à Korhogo", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.14", projetCode: "P3.PNR1.1", titre: "Organiser la 2ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Korhogo", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.15", projetCode: "P3.PNR1.1", titre: "Organiser la 3ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Korhogo", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.16", projetCode: "P3.PNR1.1", titre: "Organiser la 4ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Korhogo", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.17", projetCode: "P3.PNR1.1", titre: "Organiser la 1ière visite de collecte des données et de coaching des prestataires dans les centres franchisés à Man", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.18", projetCode: "P3.PNR1.1", titre: "Organiser la 2ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Man", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.19", projetCode: "P3.PNR1.1", titre: "Organiser la 3ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Man", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.20", projetCode: "P3.PNR1.1", titre: "Organiser la 4ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Man", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.21", projetCode: "P3.PNR1.1", titre: "Organiser la 1ière visite de collecte des données et de coaching des prestataires dans les centres franchisés à San Pedro", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.22", projetCode: "P3.PNR1.1", titre: "Organiser la 2ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à San Pedro", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.23", projetCode: "P3.PNR1.1", titre: "Organiser la 3ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à San Pedro", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.24", projetCode: "P3.PNR1.1", titre: "Organiser la 4ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à San Pedro", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.25", projetCode: "P3.PNR1.1", titre: "Organiser la 1ière visite de collecte des données et de coaching des prestataires dans les centres franchisés à Yamoussoukro", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.26", projetCode: "P3.PNR1.1", titre: "Organiser la 2ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Yamoussoukro", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.27", projetCode: "P3.PNR1.1", titre: "Organiser la 3ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Yamoussoukro", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PNR1.1-A.3.28", projetCode: "P3.PNR1.1", titre: "Organiser la 4ième visite de collecte des données et de coaching des prestataires dans les centres franchisés à Yamoussoukro", nature: "Suivi", lieu: null, budget: 67500, isParent: false },
  { code: "P3.PR1.1-A.1", projetCode: "P3.PR1.1", titre: "Elaborer des documents stratégiques", nature: null, lieu: null, budget: 2160000, isParent: true },
  { code: "P3.PR1.1-A.1.1", projetCode: "P3.PR1.1", titre: "Elaborer une stratégie de mobilisation de ressources assortie d’un plan d’actions", nature: null, lieu: "Siège", budget: 1710000, isParent: false },
  { code: "P3.PR1.1-A.1.2", projetCode: "P3.PR1.1", titre: "Elaborer une stratégie de communication assortie d’un plan de communication", nature: null, lieu: "Siège", budget: 450000, isParent: false },
  { code: "P3.PR1.2-A.1", projetCode: "P3.PR1.2", titre: "Réaliser le diagnostic organisationnel de l'AIBEF", nature: null, lieu: null, budget: 4387375, isParent: true },
  { code: "P3.PR1.2-A.1.1", projetCode: "P3.PR1.2", titre: "Recruter un consultant en développement organisationnel", nature: null, lieu: "Siège", budget: 2250000, isParent: false },
  { code: "P3.PR1.2-A.1.2", projetCode: "P3.PR1.2", titre: "Organiser une mission d’évaluation du système de gouvernance et des capacités de mobilisation de ressources", nature: null, lieu: "Siège", budget: 2137375, isParent: false },
  { code: "P3.PR1.2-A.2", projetCode: "P3.PR1.2", titre: "Organiser des ateliers de renforcement de capacités de la gouvernance et du staff", nature: null, lieu: null, budget: 12946370, isParent: true },
  { code: "P3.PR1.2-A.2.1", projetCode: "P3.PR1.2", titre: "Organiser des atelier de formation des membres de la gouvernance, du SMT et des coordonnateurs d’antennes", nature: null, lieu: "Siège", budget: 8702000, isParent: false },
  { code: "P3.PR1.2-A.2.2", projetCode: "P3.PR1.2", titre: "Organiser des Minis ateliers de restitution par région", nature: null, lieu: "Siège", budget: 4244370, isParent: false },
  { code: "P3.PR1.2-A.3", projetCode: "P3.PR1.2", titre: "Mettre en place une banque de projets", nature: null, lieu: null, budget: 3000000, isParent: true },
  { code: "P3.PR1.2-A.3.1", projetCode: "P3.PR1.2", titre: "Recruter 'un Chargé de la rédaction et la mobilisation de projets", nature: null, lieu: "Siège", budget: 3000000, isParent: false },
  { code: "P3.PR1.2-A.3.2", projetCode: "P3.PR1.2", titre: "Organiser des séances de présentation/validation de projets", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P3.PR1.2-A.4", projetCode: "P3.PR1.2", titre: "Organiser des ateliers de renforcement de capacités des acteurs du féminisme", nature: null, lieu: null, budget: 10208000, isParent: true },
  { code: "P3.PR1.2-A.4.1", projetCode: "P3.PR1.2", titre: "Organiser un atelier de formation sur les approches féministes", nature: null, lieu: "Siège", budget: 7658000, isParent: false },
  { code: "P3.PR1.2-A.4.2", projetCode: "P3.PR1.2", titre: "Organiser un atelier de formation sur les stratégies de plaidoyer", nature: null, lieu: "Siège", budget: 2550000, isParent: false },
  { code: "P3.PR1.2-A.4.3", projetCode: "P3.PR1.2", titre: "Développer une plateforme en ligne ou un groupe de discussion pour que les féministes", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P3.PR1.2-A.5", projetCode: "P3.PR1.2", titre: "Organiser des activités de sensibilisation des jeunes sur le féminisme", nature: null, lieu: null, budget: 1740000, isParent: true },
  { code: "P3.PR1.2-A.5.1", projetCode: "P3.PR1.2", titre: "Organiser une campagne de collecte de livres et de ressources pédagogique", nature: null, lieu: "Siège", budget: 1740000, isParent: false },
  { code: "P3.PR1.2-A.5.2", projetCode: "P3.PR1.2", titre: "Produire des brochures sur les approches féministes et la Charte des féministes d'Afrique", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P3.PR1.2-A.5.3", projetCode: "P3.PR1.2", titre: "Distribuer les brochures sur les approches féministes et la Charte des féministes d'Afrique", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P3.PR1.2-A.6", projetCode: "P3.PR1.2", titre: "Organiser des séances mensuelles de lecture et des tables rondes à la bibliothèque du CASEJ", nature: null, lieu: null, budget: 0, isParent: true },
  { code: "P3.PR1.2-A.6.1", projetCode: "P3.PR1.2", titre: "Organiser des séances mensuelles de lecture à la bibliothèque du CASEJ", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P3.PR1.2-A.6.2", projetCode: "P3.PR1.2", titre: "Organiser des tables rondes à la bibliothèque du CASEJ", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P3.PR1.2-A.7", projetCode: "P3.PR1.2", titre: "Animer le site web et réseaux sociaux de l'AIBEF", nature: null, lieu: null, budget: 0, isParent: true },
  { code: "P3.PR1.2-A.7.1", projetCode: "P3.PR1.2", titre: "Développer et mettre en ligne le site web de l'AIBEF", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P3.PR1.2-A.7.2", projetCode: "P3.PR1.2", titre: "Créer des pages sur les réseaux sociaux", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P3.PR1.2-A.7.3", projetCode: "P3.PR1.2", titre: "Créer les contenus digitales", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P3.PR1.2-A.7.4", projetCode: "P3.PR1.2", titre: "Animer le site web et réseaux sociaux de l'AIBEF", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P3.PR1.2-A.8", projetCode: "P3.PR1.2", titre: "Mettre en œuvre les activités de soutien au projet", nature: null, lieu: null, budget: 0, isParent: true },
  { code: "P3.PR1.2-A.8.1", projetCode: "P3.PR1.2", titre: "Recruter du personnel de soutien (Assistant Programme, Assistant Comptable)", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P3.PR1.2-A.8.2", projetCode: "P3.PR1.2", titre: "Acquérir du matériels et equipement du projet", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P3.PR1.2-A.8.3", projetCode: "P3.PR1.2", titre: "Installer et configurer l'accès Internet au CASEJ (Fibre Optique, câblage réseaux)", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P4.PNR1.1-A.1", projetCode: "P4.PNR1.1", titre: "Organiser des réunions des équipes qualité", nature: null, lieu: null, budget: 900000, isParent: true },
  { code: "P4.PNR1.1-A.1.1", projetCode: "P4.PNR1.1", titre: "Organiser la 1ière réunions des équipes qualité à la clinique de Treichville", nature: null, lieu: "Treichville", budget: 37500, isParent: false },
  { code: "P4.PNR1.1-A.1.2", projetCode: "P4.PNR1.1", titre: "Organiser la 2ième réunions des équipes qualité à la clinique de Treichville", nature: null, lieu: "Treichville", budget: 37500, isParent: false },
  { code: "P4.PNR1.1-A.1.3", projetCode: "P4.PNR1.1", titre: "Organiser la 3ième réunions des équipes qualité à la clinique de Treichville", nature: null, lieu: "Treichville", budget: 37500, isParent: false },
  { code: "P4.PNR1.1-A.1.4", projetCode: "P4.PNR1.1", titre: "Organiser la 4ième réunions des équipes qualité à la clinique de Treichville", nature: null, lieu: "Treichville", budget: 37500, isParent: false },
  { code: "P4.PNR1.1-A.1.5", projetCode: "P4.PNR1.1", titre: "Organiser la 1ière réunions des équipes qualité à la clinique du CASEJ", nature: null, lieu: "Yopougon", budget: 37500, isParent: false },
  { code: "P4.PNR1.1-A.1.6", projetCode: "P4.PNR1.1", titre: "Organiser la 2ième réunions des équipes qualité à la clinique du CASEJ", nature: null, lieu: "Yopougon", budget: 37500, isParent: false },
  { code: "P4.PNR1.1-A.1.7", projetCode: "P4.PNR1.1", titre: "Organiser la 3ième réunions des équipes qualité à la clinique du CASEJ", nature: null, lieu: "Yopougon", budget: 37500, isParent: false },
  { code: "P4.PNR1.1-A.1.8", projetCode: "P4.PNR1.1", titre: "Organiser la 4ième réunions des équipes qualité à la clinique du CASEJ", nature: null, lieu: "Yopougon", budget: 37500, isParent: false },
  { code: "P4.PNR1.1-A.1.9", projetCode: "P4.PNR1.1", titre: "Organiser la 1ière réunions des équipes qualité à la clinique de Bouaké", nature: null, lieu: "Bouaké", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.10", projetCode: "P4.PNR1.1", titre: "Organiser la 2ième réunions des équipes qualité à la clinique de Bouaké", nature: null, lieu: "Bouaké", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.11", projetCode: "P4.PNR1.1", titre: "Organiser la 3ième réunions des équipes qualité à la clinique de Bouaké", nature: null, lieu: "Bouaké", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.12", projetCode: "P4.PNR1.1", titre: "Organiser la 4ième réunions des équipes qualité à la clinique de Bouaké", nature: null, lieu: "Bouaké", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.13", projetCode: "P4.PNR1.1", titre: "Organiser la 1ière réunions des équipes qualité à la clinique de Daloa", nature: null, lieu: "Daloa", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.14", projetCode: "P4.PNR1.1", titre: "Organiser la 2ième réunions des équipes qualité à la clinique de Daloa", nature: null, lieu: "Daloa", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.15", projetCode: "P4.PNR1.1", titre: "Organiser la 3ième réunions des équipes qualité à la clinique de Daloa", nature: null, lieu: "Daloa", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.16", projetCode: "P4.PNR1.1", titre: "Organiser la 4ième réunions des équipes qualité à la clinique de Daloa", nature: null, lieu: "Daloa", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.17", projetCode: "P4.PNR1.1", titre: "Organiser la 1ière réunions des équipes qualité à la clinique de Korhogo", nature: null, lieu: "Korhogo", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.18", projetCode: "P4.PNR1.1", titre: "Organiser la 2ième réunions des équipes qualité à la clinique de Korhogo", nature: null, lieu: "Korhogo", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.19", projetCode: "P4.PNR1.1", titre: "Organiser la 3ième réunions des équipes qualité à la clinique de Korhogo", nature: null, lieu: "Korhogo", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.20", projetCode: "P4.PNR1.1", titre: "Organiser la 4ième réunions des équipes qualité à la clinique de Korhogo", nature: null, lieu: "Korhogo", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.21", projetCode: "P4.PNR1.1", titre: "Organiser la 1ière réunions des équipes qualité à la clinique de Man", nature: null, lieu: "Man", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.22", projetCode: "P4.PNR1.1", titre: "Organiser la 2ième réunions des équipes qualité à la clinique de Man", nature: null, lieu: "Man", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.23", projetCode: "P4.PNR1.1", titre: "Organiser la 3ième réunions des équipes qualité à la clinique de Man", nature: null, lieu: "Man", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.24", projetCode: "P4.PNR1.1", titre: "Organiser la 4ième réunions des équipes qualité à la clinique de Man", nature: null, lieu: "Man", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.25", projetCode: "P4.PNR1.1", titre: "Organiser la 1ière réunions des équipes qualité à la clinique de San Pedro", nature: null, lieu: "San Pedro", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.26", projetCode: "P4.PNR1.1", titre: "Organiser la 2ième réunions des équipes qualité à la clinique de San Pedro", nature: null, lieu: "San Pedro", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.27", projetCode: "P4.PNR1.1", titre: "Organiser la 3ième réunions des équipes qualité à la clinique de San Pedro", nature: null, lieu: "San Pedro", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.28", projetCode: "P4.PNR1.1", titre: "Organiser la 4ième réunions des équipes qualité à la clinique de San Pedro", nature: null, lieu: "San Pedro", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.29", projetCode: "P4.PNR1.1", titre: "Organiser la 1ière réunions des équipes qualité à la clinique de Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.30", projetCode: "P4.PNR1.1", titre: "Organiser la 2ième réunions des équipes qualité à la clinique de Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.31", projetCode: "P4.PNR1.1", titre: "Organiser la 3ième réunions des équipes qualité à la clinique de Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.1.32", projetCode: "P4.PNR1.1", titre: "Organiser la 4ième réunions des équipes qualité à la clinique de Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 25000, isParent: false },
  { code: "P4.PNR1.1-A.2", projetCode: "P4.PNR1.1", titre: "Réaliser des activités de suivi en ligne, des recommandations post accréditation", nature: null, lieu: null, budget: 1000000, isParent: true },
  { code: "P4.PNR1.1-A.2.1", projetCode: "P4.PNR1.1", titre: "Réaliser la 1ière activité de suivi en ligne, des recommandations post accréditation", nature: null, lieu: null, budget: 500000, isParent: false },
  { code: "P4.PNR1.1-A.2.2", projetCode: "P4.PNR1.1", titre: "Réaliser la 2ième activité de suivi en ligne, des recommandations post accréditation", nature: null, lieu: null, budget: 500000, isParent: false },
  { code: "P4.PNR1.1-A.3", projetCode: "P4.PNR1.1", titre: "Organiser des ateliers", nature: null, lieu: null, budget: 9607000, isParent: true },
  { code: "P4.PNR1.1-A.3.1", projetCode: "P4.PNR1.1", titre: "Organiser un atelier de révision des documents de poltiques de l'AIBEF", nature: null, lieu: null, budget: 9607000, isParent: false },
  { code: "P4.PNR1.2-A.1", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires", nature: null, lieu: null, budget: 1050000, isParent: true },
  { code: "P4.PNR1.2-A.1.1", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Adultes  à Abidjan", nature: null, lieu: "Abidjan", budget: 100000, isParent: false },
  { code: "P4.PNR1.2-A.1.2", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Adultes  à Bondoukou", nature: null, lieu: "Bondoukou", budget: 75000, isParent: false },
  { code: "P4.PNR1.2-A.1.3", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Adultes à Bouaké", nature: null, lieu: "Bouaké", budget: 75000, isParent: false },
  { code: "P4.PNR1.2-A.1.4", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Adultes  à Daloa", nature: null, lieu: "Daloa", budget: 75000, isParent: false },
  { code: "P4.PNR1.2-A.1.5", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Adultes à Korhogo", nature: null, lieu: "Korhogo", budget: 75000, isParent: false },
  { code: "P4.PNR1.2-A.1.6", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Adultes à Man", nature: null, lieu: "Man", budget: 75000, isParent: false },
  { code: "P4.PNR1.2-A.1.7", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Adultes à San Pedro", nature: null, lieu: "San Pedro", budget: 75000, isParent: false },
  { code: "P4.PNR1.2-A.1.8", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Adultes à Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 75000, isParent: false },
  { code: "P4.PNR1.2-A.1.9", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Jeunes à Abidjan", nature: null, lieu: "Abidjan", budget: 75000, isParent: false },
  { code: "P4.PNR1.2-A.1.10", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Jeunes à Bondoukou", nature: null, lieu: "Bondoukou", budget: 50000, isParent: false },
  { code: "P4.PNR1.2-A.1.11", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Jeunes à Bouaké", nature: null, lieu: "Bouaké", budget: 50000, isParent: false },
  { code: "P4.PNR1.2-A.1.12", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Jeunes à Daloa", nature: null, lieu: "Daloa", budget: 50000, isParent: false },
  { code: "P4.PNR1.2-A.1.13", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Jeunes à Korhogo", nature: null, lieu: "Korhogo", budget: 50000, isParent: false },
  { code: "P4.PNR1.2-A.1.14", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Jeunes à Man", nature: null, lieu: "Man", budget: 50000, isParent: false },
  { code: "P4.PNR1.2-A.1.15", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Jeunes à San Pedro", nature: null, lieu: "San Pedro", budget: 50000, isParent: false },
  { code: "P4.PNR1.2-A.1.16", projetCode: "P4.PNR1.2", titre: "Organiser les sessions d’orientation des volontaires Jeunes à Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 50000, isParent: false },
  { code: "P4.PNR1.2-A.2", projetCode: "P4.PNR1.2", titre: "Organiser les réunions statutaires des membres volontaires", nature: null, lieu: null, budget: 7700500, isParent: true },
  { code: "P4.PNR1.2-A.2.1", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du CEN", nature: null, lieu: "Siège", budget: 60000, isParent: false },
  { code: "P4.PNR1.2-A.2.2", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du CEN", nature: null, lieu: "Siège", budget: 60000, isParent: false },
  { code: "P4.PNR1.2-A.2.3", projetCode: "P4.PNR1.2", titre: "Organiser la 3ième réunion du CEN", nature: null, lieu: "Siège", budget: 60000, isParent: false },
  { code: "P4.PNR1.2-A.2.4", projetCode: "P4.PNR1.2", titre: "Organiser la 4ième réunion du CEN", nature: null, lieu: "Siège", budget: 60000, isParent: false },
  { code: "P4.PNR1.2-A.2.5", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR d'Abidjan", nature: null, lieu: "Abidjan", budget: 25000, isParent: false },
  { code: "P4.PNR1.2-A.2.6", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR d'Abidjan", nature: null, lieu: "Abidjan", budget: 25000, isParent: false },
  { code: "P4.PNR1.2-A.2.7", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR de Bondoukou", nature: null, lieu: "Bondoukou", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.8", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR de Bondoukou", nature: null, lieu: "Bondoukou", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.9", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR de Bouaké", nature: null, lieu: "Bouaké", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.10", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR de Bouaké", nature: null, lieu: "Bouaké", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.11", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR de Daloa", nature: null, lieu: "Daloa", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.12", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR de Daloa", nature: null, lieu: "Daloa", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.13", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR de Korhogo", nature: null, lieu: "Korhogo", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.14", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR de Korhogo", nature: null, lieu: "Korhogo", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.15", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR de Man", nature: null, lieu: "Man", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.16", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR de Man", nature: null, lieu: "Man", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.17", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR de San Pedro", nature: null, lieu: "San Pedro", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.18", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR de San Pedro", nature: null, lieu: "San Pedro", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.19", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR de Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.20", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR de Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.21", projetCode: "P4.PNR1.2", titre: "Organiser une Assemblée Générale  Nationale Ordinaire", nature: null, lieu: "Siège", budget: 3189000, isParent: false },
  { code: "P4.PNR1.2-A.2.22", projetCode: "P4.PNR1.2", titre: "Organiser une Assemblée Générale Régionale ordinaire d'Abidjan", nature: null, lieu: "Abidjan", budget: 160000, isParent: false },
  { code: "P4.PNR1.2-A.2.23", projetCode: "P4.PNR1.2", titre: "Organiser une Assemblée Générale Régionale ordinaire de Bondoukou", nature: null, lieu: "Bondoukou", budget: 135000, isParent: false },
  { code: "P4.PNR1.2-A.2.24", projetCode: "P4.PNR1.2", titre: "Organiser une Assemblée Générale Régionale ordinaire de Bouaké", nature: null, lieu: "Bouaké", budget: 135000, isParent: false },
  { code: "P4.PNR1.2-A.2.25", projetCode: "P4.PNR1.2", titre: "Organiser une Assemblée Générale Régionale ordinaire de Daloa", nature: null, lieu: "Daloa", budget: 135000, isParent: false },
  { code: "P4.PNR1.2-A.2.26", projetCode: "P4.PNR1.2", titre: "Organiser une Assemblée Générale Régionale ordinaire de Korhogo", nature: null, lieu: "Korhogo", budget: 135000, isParent: false },
  { code: "P4.PNR1.2-A.2.27", projetCode: "P4.PNR1.2", titre: "Organiser une Assemblée Générale Régionale ordinaire de Man", nature: null, lieu: "Man", budget: 135000, isParent: false },
  { code: "P4.PNR1.2-A.2.28", projetCode: "P4.PNR1.2", titre: "Organiser une Assemblée Générale Régionale ordinaire de San Pedro", nature: null, lieu: "San Pedro", budget: 135000, isParent: false },
  { code: "P4.PNR1.2-A.2.29", projetCode: "P4.PNR1.2", titre: "Organiser une Assemblée Générale Régionale ordinaire de Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 135000, isParent: false },
  { code: "P4.PNR1.2-A.2.30", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BN MAJ", nature: null, lieu: "Siège", budget: 210000, isParent: false },
  { code: "P4.PNR1.2-A.2.31", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BN MAJ", nature: null, lieu: "Siège", budget: 210000, isParent: false },
  { code: "P4.PNR1.2-A.2.32", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR MAJ d'Abidjan", nature: null, lieu: "Abidjan", budget: 25000, isParent: false },
  { code: "P4.PNR1.2-A.2.33", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR MAJ d'Abidjan", nature: null, lieu: "Abidjan", budget: 25000, isParent: false },
  { code: "P4.PNR1.2-A.2.34", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR MAJ de Bondoukou", nature: null, lieu: "Bondoukou", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.35", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR MAJ de Bondoukou", nature: null, lieu: "Bondoukou", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.36", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR MAJ de Bouaké", nature: null, lieu: "Bouaké", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.37", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR MAJ de Bouaké", nature: null, lieu: "Bouaké", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.38", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR MAJ de Daloa", nature: null, lieu: "Daloa", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.39", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR MAJ de Daloa", nature: null, lieu: "Daloa", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.40", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR MAJ de Korhogo", nature: null, lieu: "Korhogo", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.41", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR MAJ de Korhogo", nature: null, lieu: "Korhogo", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.42", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR MAJ de Man", nature: null, lieu: "Man", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.43", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR MAJ de Man", nature: null, lieu: "Man", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.44", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR MAJ de San Pedro", nature: null, lieu: "San Pedro", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.45", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR MAJ de San Pedro", nature: null, lieu: "San Pedro", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.46", projetCode: "P4.PNR1.2", titre: "Organiser la 1ière réunion du BR MAJ de Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.47", projetCode: "P4.PNR1.2", titre: "Organiser la 2ième réunion du BR MAJ de Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 15000, isParent: false },
  { code: "P4.PNR1.2-A.2.48", projetCode: "P4.PNR1.2", titre: "Organiser un Forum national des jeunes", nature: null, lieu: "Siège", budget: 1914000, isParent: false },
  { code: "P4.PNR1.2-A.2.49", projetCode: "P4.PNR1.2", titre: "Organiser un Forum régional des jeunes d'Abidjan", nature: null, lieu: "Abidjan", budget: 50000, isParent: false },
  { code: "P4.PNR1.2-A.2.50", projetCode: "P4.PNR1.2", titre: "Organiser un Forum régional des jeunes de Bondoukou", nature: null, lieu: "Bondoukou", budget: 37500, isParent: false },
  { code: "P4.PNR1.2-A.2.51", projetCode: "P4.PNR1.2", titre: "Organiser un Forum régional des jeunes de Bouaké", nature: null, lieu: "Bouaké", budget: 37500, isParent: false },
  { code: "P4.PNR1.2-A.2.52", projetCode: "P4.PNR1.2", titre: "Organiser un Forum régional des jeunes de Daloa", nature: null, lieu: "Daloa", budget: 37500, isParent: false },
  { code: "P4.PNR1.2-A.2.53", projetCode: "P4.PNR1.2", titre: "Organiser un Forum régional des jeunes de Korhogo", nature: null, lieu: "Korhogo", budget: 37500, isParent: false },
  { code: "P4.PNR1.2-A.2.54", projetCode: "P4.PNR1.2", titre: "Organiser un Forum régional des jeunes de Man", nature: null, lieu: "Man", budget: 37500, isParent: false },
  { code: "P4.PNR1.2-A.2.55", projetCode: "P4.PNR1.2", titre: "Organiser un Forum régional des jeunes de San Pedro", nature: null, lieu: "San Pedro", budget: 37500, isParent: false },
  { code: "P4.PNR1.2-A.2.56", projetCode: "P4.PNR1.2", titre: "Organiser un Forum régional des jeunes de Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 37500, isParent: false },
  { code: "P4.PNR1.2-A.3", projetCode: "P4.PNR1.2", titre: "Organiser des missions des instances des membres volontaires", nature: null, lieu: null, budget: 2549662, isParent: true },
  { code: "P4.PNR1.2-A.3.1", projetCode: "P4.PNR1.2", titre: "Organiser une une mission du CEN et du DE dans les antennes régionales", nature: null, lieu: "Siège", budget: 2549662, isParent: false },
  { code: "P4.PNR1.2-A.4", projetCode: "P4.PNR1.2", titre: "Organiser les activités avec les membres volontaires", nature: null, lieu: null, budget: 7162780, isParent: true },
  { code: "P4.PNR1.2-A.4.1", projetCode: "P4.PNR1.2", titre: "Organiser  la 1ière journées portes ouvertes à Daloa", nature: null, lieu: "Daloa", budget: 155000, isParent: false },
  { code: "P4.PNR1.2-A.4.2", projetCode: "P4.PNR1.2", titre: "Organiser  la 2ième journées portes ouvertes à Daloa", nature: null, lieu: "Daloa", budget: 155000, isParent: false },
  { code: "P4.PNR1.2-A.4.3", projetCode: "P4.PNR1.2", titre: "Organiser  la 1ière journées portes ouvertes à Korhogo", nature: null, lieu: "Korhogo", budget: 155000, isParent: false },
  { code: "P4.PNR1.2-A.4.4", projetCode: "P4.PNR1.2", titre: "Organiser  la 2ième journées portes ouvertes à Korhogo", nature: null, lieu: "Korhogo", budget: 155000, isParent: false },
  { code: "P4.PNR1.2-A.4.5", projetCode: "P4.PNR1.2", titre: "Organiser  la 1ière journées portes ouvertes à San Pedro", nature: null, lieu: "San Pedro", budget: 155000, isParent: false },
  { code: "P4.PNR1.2-A.4.6", projetCode: "P4.PNR1.2", titre: "Organiser  la 2ième journées portes ouvertes à San Pedro", nature: null, lieu: "San Pedro", budget: 155000, isParent: false },
  { code: "P4.PNR1.2-A.4.7", projetCode: "P4.PNR1.2", titre: "Organiser  la 1ière journées portes ouvertes à Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 155000, isParent: false },
  { code: "P4.PNR1.2-A.4.8", projetCode: "P4.PNR1.2", titre: "Organiser  la 2ième journées portes ouvertes à Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 155000, isParent: false },
  { code: "P4.PNR1.2-A.4.9", projetCode: "P4.PNR1.2", titre: "Organiser  un gala de bienfaisance à Abidjan", nature: null, lieu: "Abidjan", budget: 4327780, isParent: false },
  { code: "P4.PNR1.2-A.4.10", projetCode: "P4.PNR1.2", titre: "Organiser  un gala de bienfaisance à Korhogo", nature: null, lieu: "Korhogo", budget: 395000, isParent: false },
  { code: "P4.PNR1.2-A.4.10", projetCode: "P4.PNR1.2", titre: "Organiser la SR fun days à Abidjan", nature: null, lieu: "Siège", budget: 1200000, isParent: false },
  { code: "P4.PNR1.3-A.1", projetCode: "P4.PNR1.3", titre: "Faire fonctionner l’administration de l’AIBEF", nature: null, lieu: null, budget: 132987490, isParent: true },
  { code: "P4.PNR1.3-A.1.1", projetCode: "P4.PNR1.3", titre: "Couvrir les charges de fonctionnement de l’administration de l’AIBEF", nature: null, lieu: "Siège", budget: 131267490, isParent: false },
  { code: "P4.PNR1.3-A.1.2", projetCode: "P4.PNR1.3", titre: "Réaliser l'inventaires des immobilisations à Abidjan", nature: null, lieu: "Abidjan", budget: 700000, isParent: false },
  { code: "P4.PNR1.3-A.1.3", projetCode: "P4.PNR1.3", titre: "Réaliser l'inventaires des immobilisations à Bondoukou", nature: null, lieu: "Bondoukou", budget: 10000, isParent: false },
  { code: "P4.PNR1.3-A.1.4", projetCode: "P4.PNR1.3", titre: "Réaliser l'inventaires des immobilisations à Bouaké", nature: null, lieu: "Bouaké", budget: 190000, isParent: false },
  { code: "P4.PNR1.3-A.1.5", projetCode: "P4.PNR1.3", titre: "Réaliser l'inventaires des immobilisations à Daloa", nature: null, lieu: "Daloa", budget: 220000, isParent: false },
  { code: "P4.PNR1.3-A.1.6", projetCode: "P4.PNR1.3", titre: "Réaliser l'inventaires des immobilisations à Korhogo", nature: null, lieu: "Korhogo", budget: 220000, isParent: false },
  { code: "P4.PNR1.3-A.1.7", projetCode: "P4.PNR1.3", titre: "Réaliser l'inventaires des immobilisations à Man", nature: null, lieu: "Man", budget: 30000, isParent: false },
  { code: "P4.PNR1.3-A.1.8", projetCode: "P4.PNR1.3", titre: "Réaliser l'inventaires des immobilisations à San Pedro", nature: null, lieu: "San Pedro", budget: 200000, isParent: false },
  { code: "P4.PNR1.3-A.1.9", projetCode: "P4.PNR1.3", titre: "Réaliser l'inventaires des immobilisations à Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 150000, isParent: false },
  { code: "P4.PNR1.3-A.2", projetCode: "P4.PNR1.3", titre: "Organiser des activités de motivation du Personnel", nature: null, lieu: null, budget: 1030000, isParent: true },
  { code: "P4.PNR1.3-A.2.1", projetCode: "P4.PNR1.3", titre: "Organiser la journée du bien être des travailleurs à Abidjan", nature: null, lieu: "Abidjan", budget: 500000, isParent: false },
  { code: "P4.PNR1.3-A.2.2", projetCode: "P4.PNR1.3", titre: "Organiser la journée du bien être des travailleurs à Bondoukou", nature: null, lieu: "Bondoukou", budget: 50000, isParent: false },
  { code: "P4.PNR1.3-A.2.3", projetCode: "P4.PNR1.3", titre: "Organiser la journée du bien être des travailleurs à Bouaké", nature: null, lieu: "Bouaké", budget: 80000, isParent: false },
  { code: "P4.PNR1.3-A.2.4", projetCode: "P4.PNR1.3", titre: "Organiser la journée du bien être des travailleurs à Daloa", nature: null, lieu: "Daloa", budget: 100000, isParent: false },
  { code: "P4.PNR1.3-A.2.5", projetCode: "P4.PNR1.3", titre: "Organiser la journée du bien être des travailleurs à Korhogo", nature: null, lieu: "Korhogo", budget: 100000, isParent: false },
  { code: "P4.PNR1.3-A.2.6", projetCode: "P4.PNR1.3", titre: "Organiser la journée du bien être des travailleurs à Man", nature: null, lieu: "Man", budget: 50000, isParent: false },
  { code: "P4.PNR1.3-A.2.7", projetCode: "P4.PNR1.3", titre: "Organiser la journée du bien être des travailleurs à San Pedro", nature: null, lieu: "San Pedro", budget: 75000, isParent: false },
  { code: "P4.PNR1.3-A.2.8", projetCode: "P4.PNR1.3", titre: "Organiser la journée du bien être des travailleurs à Yamoussoukro", nature: null, lieu: "Yamoussoukro", budget: 75000, isParent: false },
  { code: "P4.PNR1.3-A.3", projetCode: "P4.PNR1.3", titre: "Organiser des sessions de renforcement des compétences du personnel", nature: null, lieu: null, budget: 11195000, isParent: true },
  { code: "P4.PNR1.3-A.3.1", projetCode: "P4.PNR1.3", titre: "Organiser une session de formation des membres volontaires et du staff de l’AIBEF sur le Genre, la diversité sexuelle et l'inclusion au travail", nature: null, lieu: "Siège", budget: 3791000, isParent: false },
  { code: "P4.PNR1.3-A.3.2", projetCode: "P4.PNR1.3", titre: "Organiser une session de Team building avec le staff", nature: null, lieu: "Siège", budget: 6219000, isParent: false },
  { code: "P4.PNR1.3-A.3.3", projetCode: "P4.PNR1.3", titre: "Participer à d'autres sessions de formation organisées par les PTF", nature: null, lieu: "Siège", budget: 0, isParent: false },
  { code: "P4.PNR1.3-A.3.4", projetCode: "P4.PNR1.3", titre: "Participer aux journées annuelles du RIGRH", nature: null, lieu: "Siège", budget: 1185000, isParent: false },
  { code: "P4.PNR1.3-A.4", projetCode: "P4.PNR1.3", titre: "Organiser des réunions du Personnel", nature: null, lieu: null, budget: 785000, isParent: true },
  { code: "P4.PNR1.3-A.4.1", projetCode: "P4.PNR1.3", titre: "Organiser à la réunion du Personnel", nature: null, lieu: "Siège", budget: 785000, isParent: false },
  { code: "P4.PNR1.3-A.5", projetCode: "P4.PNR1.3", titre: "Organiser des missions de supervision", nature: null, lieu: null, budget: 3069662, isParent: true },
  { code: "P4.PNR1.3-A.5.1", projetCode: "P4.PNR1.3", titre: "Organiser une mission du DE/RH dans les Antennes régionales de l'AIBEF", nature: null, lieu: "Siège", budget: 3069662, isParent: false },
  { code: "P4.PNR1.4-A.1", projetCode: "P4.PNR1.4", titre: "Organiser les activités du Learning Center", nature: null, lieu: null, budget: 15360264, isParent: true },
  { code: "P4.PNR1.4-A.1.1", projetCode: "P4.PNR1.4", titre: "Organiser les activités du Learning Center", nature: null, lieu: "Siège", budget: 15360264, isParent: false },
];

async function main() {
  console.log("Seeding activites (2026)...");

  // Get all projects by code
  const projets = await prisma.projet.findMany({ where: { isActive: true } });
  const projetMap = new Map(projets.map((p) => [p.code, p.id]));

  // Get admin user as createur (first SUPER_ADMIN or any admin)
  const adminUser = await prisma.user.findFirst({
    where: { role: "SUPER_ADMIN" },
  });
  if (!adminUser) {
    console.error("No SUPER_ADMIN user found. Please seed users first.");
    process.exit(1);
  }

  let created = 0;
  let skipped = 0;

  for (const act of ACTIVITES) {
    const projetId = projetMap.get(act.projetCode);
    if (!projetId) {
      console.warn("  [SKIP] Project not found: " + act.projetCode + " for " + act.code);
      skipped++;
      continue;
    }

    // Check if activity already exists (by titre + projet)
    const existing = await prisma.activite.findFirst({
      where: {
        titre: act.titre,
        projetId: projetId,
      },
    });

    if (existing) {
      // Update budget if changed
      await prisma.activite.update({
        where: { id: existing.id },
        data: {
          budget: act.budget || undefined,
          observations: act.code,
        },
      });
      skipped++;
      continue;
    }

    const descParts: string[] = [];
    if (act.nature) descParts.push("Nature: " + act.nature);
    if (act.lieu) descParts.push("Lieu: " + act.lieu);

    await prisma.activite.create({
      data: {
        titre: act.titre,
        description: descParts.length > 0 ? descParts.join(" | ") : undefined,
        type: "PONCTUELLE",
        statut: "PLANIFIEE",
        dateDebut: new Date("2026-01-01"),
        dateFin: new Date("2026-12-31"),
        budget: act.budget || undefined,
        observations: act.code,
        projetId: projetId,
        createurId: adminUser.id,
      },
    });
    created++;
  }

  console.log("\nDone! Created: " + created + ", Updated/Skipped: " + skipped);
  console.log("Total activities in plan: " + ACTIVITES.length);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
